# Generated by Django 4.2.1 on 2023-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterClone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followedBy', to='TwitterClone.profile'),
        ),
    ]
