# Generated by Django 4.2.1 on 2023-05-18 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TwitterClone', '0003_meep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meep',
            new_name='Meeps',
        ),
    ]
