# Generated by Django 4.1.4 on 2023-05-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterClone', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='profileImage',
        ),
    ]
