# Generated by Django 4.1.4 on 2023-05-19 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TwitterClone', '0006_rename_profile_image_profile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeps',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='meepLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
