# Generated by Django 4.1.4 on 2023-05-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterClone', '0007_meeps_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileBio',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
